export { default as HomePage } from './HomePage'
export { default as Carousel } from './Carousel'
export { default as HomePageCard } from './HomePageCard'
export { default as CaraouselCategory } from './CarouselCategory'
export { default as CaraouselProduct } from './CarouselProduct'
export { default as NavBar } from "./NavBar"
export { default as Search } from "./Search"
export { default as ProductPage } from "./ProductPage"
export { default as SearchResult } from "./SearchResult"
export { default as CheckOut } from "./CheckOut"